name: Sudo Test
on: [workflow_dispatch]

jobs:
  check-sudo:
    runs-on: self-hosted
    steps:
      - name: Who am I
        run: whoami

      - name: Check sudo permissions
        run: sudo -l

      - name: Test passwordless sudo
        run: sudo -n whoami
